language: python

python:
  - 3.8

jobs:
  include:
    - env: venv_name=virtualenv testcmd=test
    - env: venv_name=virtualenv-dev testcmd=test-dev

install:
  - make $venv_name

script:
  - make $testcmd

branches:
  only:
  - main

after success:
  - make run_codecov
