language: python

python:
  - 3.8

jobs:
  include:
    - env: venv-name=virtualenv
    - env: venv-name=virtualenv-dev

install:
  - make $venv-name

script:
  - make test

branches:
  only:
  - main

after success:
  - make run_codecov
