stages:
  preprocess_wellcome_science:
    cmd: grants_tagger preprocess wellcome-science data/raw/science_tags_full_version.xlsx
      data/processed/science_grants_tagged_title_synopsis.jsonl
    deps:
    - data/raw/science_tags_full_version.xlsx
    - grants_tagger/preprocess.py
    params:
    - preprocess_wellcome_science.text_cols
    - preprocess_wellcome_science.meta_cols
    outs:
    - data/processed/science_grants_tagged_title_synopsis.jsonl
  train_tfidf_svm:
    cmd: grants_tagger train data/processed/science_grants_tagged_title_synopsis.jsonl
      models/label_binarizer.pkl models/tfidf-svm.pkl --approach tfidf-svm --train-info results/tfidf_svm_train_info.json
    deps:
    - data/processed/science_grants_tagged_title_synopsis.jsonl
    - grants_tagger/train.py
    params:
    - train.tfidf-svm.tfidf.min_df
    - train.tfidf-svm.svm__estimator.class_weight
    - train.tfidf-svm.tfidf.ngram_range
    outs:
    - models/label_binarizer.pkl
    - models/tfidf-svm.pkl
    metrics:
      - results/tfidf_svm_train_info.json:
          cache: false
  evaluate_tfidf_svm:
    cmd: grants_tagger evaluate model tfidf-svm models/tfidf-svm.pkl data/processed/science_grants_tagged_title_synopsis.jsonl
      models/label_binarizer.pkl --results-path results/tfidf_svm.json
    deps:
    - grants_tagger/evaluate_model.py
    - models/label_binarizer.pkl
    - models/tfidf-svm.pkl
    metrics:
    - results/tfidf_svm.json:
        cache: false
  train_scibert:
    cmd: grants_tagger train data/processed/science_grants_tagged_title_synopsis.jsonl
      models/label_binarizer.pkl models/scibert --approach scibert --train-info results/scibert_train_info.json
    deps:
    - data/processed/science_grants_tagged_title_synopsis.jsonl
    - grants_tagger/train.py
    params:
    - train.scibert.validation_split
    - train.scibert.learning_rate
    - train.scibert.epochs
    outs:
    - models/scibert
  evaluate_scibert:
    cmd: grants_tagger evaluate model scibert models/scibert data/processed/science_grants_tagged_title_synopsis.jsonl
      models/label_binarizer.pkl --results-path results/scibert.json
    deps:
    - grants_tagger/evaluate_model.py
    - models/label_binarizer.pkl
    - models/scibert
    metrics:
    - results/scibert.json:
        cache: false
#  train_science_ensemble:
#    cmd: grants_tagger train data/processed/science_grants_tagged_title_synopsis.jsonl
#      models/label_binarizer-2021.04.0.pkl models/science_ensemble-2021.04.0 --approach science-ensemble
#    deps:
#    - data/processed/science_grants_tagged_title_synopsis.jsonl
#    - grants_tagger/train.py
#    params:
#    - train.tfidf-svm.tfidf.min_df
#    - train.tfidf-svm.svm__estimator.class_weight
#    - train.tfidf-svm.tfidf.ngram_range
#    - train.scibert.validation_split
#    - train.scibert.learning_rate
#    - train.scibert.epochs
#    outs:
#    - models/science_ensemble-2021.04.0
  evaluate_science_ensemble:
    cmd: grants_tagger evaluate model science-ensemble models/tfidf-svm.pkl,models/scibert
      data/processed/science_grants_tagged_title_synopsis.jsonl models/label_binarizer.pkl
      --results-path results/science_ensemble.json
    deps:
    - grants_tagger/evaluate_model.py
    - models/tfidf-svm.pkl
    - models/scibert
    - models/label_binarizer.pkl
    #- models/label_binarizer-2021.04.0.pkl
    #- models/science_ensemble-2021.04.0
    metrics:
    - results/science_ensemble.json:
        cache: false
  preprocess_bioasq_mesh:
    cmd: grants_tagger preprocess bioasq-mesh data/raw/allMeSH_2021.json data/processed/mesh2021.jsonl --test-split 0.01
    deps:
    - data/raw/allMeSH_2021.json
    - grants_tagger/preprocess_mesh.py
    outs:
    - data/processed/train_mesh2021.jsonl
    - data/processed/test_mesh2021.jsonl
  train_mesh_xlinear:
    cmd: grants_tagger train data/processed/train_mesh2021.jsonl
      models/xlinear/label_binarizer.pkl models/xlinear/model
      --approach mesh-xlinear --sparse-labels --train-info results/mesh_xlinear_train_info.json
    deps:
    - data/processed/test_mesh2021.jsonl
    - grants_tagger/train.py
    - grants_tagger/models/mesh_xlinear.py
    params:
    - train.mesh-xlinear.tfidf.stop_words
    - train.mesh-xlinear.tfidf.min_df
    - train.mesh-xlinear.tfidf.max_df
    - train.mesh-xlinear.tfidf.max_features
    - train.mesh-xlinear.tfidf.ngram_range
    - train.mesh-xlinear.tfidf.lowercase
    - train.mesh-xlinear.xlinear.cluster_chain
    - train.mesh-xlinear.xlinear.negative_sampling_scheme
    - train.mesh-xlinear.xlinear.beam_size
    - train.mesh-xlinear.xlinear.only_topk
    - train.mesh-xlinear.xlinear.min_weight_value
    outs:
    - models/xlinear/label_binarizer.pkl
    - models/xlinear/model
  evaluate_mesh_xlinear:
    cmd: grants_tagger evaluate model mesh-xlinear models/xlinear/model
      data/processed/test_mesh2021.jsonl models/xlinear/label_binarizer.pkl
      --results-path results/mesh_xlinear.json --no-split-data
    deps:
    - grants_tagger/evaluate_model.py
    - models/xlinear/model
    - models/xlinear/label_binarizer.pkl
    metrics:
    - results/mesh_xlinear.json:
        cache: false
  filter_mesh_tags:
    cmd: python grants_tagger/filter_mesh_tags.py data/raw/desc2021.xml data/processed/mesh_disease_tags.csv
    deps:
    - data/raw/desc2021.xml
    outs:
    - data/processed/mesh_disease_tags.csv
  evaluate_mesh_xlinear_on_grants:
    cmd: grants_tagger evaluate model mesh-xlinear models/xlinear/model
      data/raw/disease_tags_validation_grants.xlsx models/xlinear/label_binarizer.pkl
      --results-path results/mesh_xlinear_on_grants.json --grants
      --mesh-tags-path data/processed/mesh_disease_tags.csv
    deps:
    - data/raw/disease_tags_validation_grants.xlsx
    - data/processed/mesh_disease_tags.csv
    - grants_tagger/evaluate_mesh_on_grants.py
    - models/xlinear/model
    - models/xlinear/label_binarizer.pkl
    metrics:
    - results/mesh_xlinear_on_grants.json:
        cache: false

  get_grants:
    cmd: python scripts/get_grants.py
    deps:
    - scripts/get_grants.py
    outs:
    - data/raw/grants.csv
  generate_validation_data_xlinear:
    cmd: python scripts/generate_validation_data_xlinear.py
    deps:
    - scripts/generate_validation_data_xlinear.py
    - data/raw/grants.csv
    - data/interim/mesh_pipeline_result.csv
    outs:
    - data/processed/merged_mesh_predictions_mesh_xlinear_for_validation.csv
