preprocess_wellcome_science:
  text_cols: "Title,Synopsis"
  meta_cols: "Grant_ID,Title"
train:
  tfidf-svm:
    tfidf:
      min_df: 5
      ngram_range: [1,2]
    svm__estimator:
      class_weight: "balanced"
  scibert:
    validation_split: 0.10
    learning_rate: 0.00002
    epochs: 10
  mesh-xlinear:
    tfidf:
      stop_words: "english"
      min_df: 5
      max_df: 1.0
      max_features: 400_000
      ngram_range: [1,1]
      lowercase: True
    xlinear:
      cluster_chain: True
      negative_sampling_scheme: "tfn"
      beam_size: 10
      only_topk: 20
      min_weight_value: 0.1
